### ISSUE TITLE
Using cachedGauge with Futures

### ISSUE THREAD

**Issue by GEverding** [erikvanoosten/metrics-scala#225]
Hi, 

How can I use cachedGauge with function that returns a Future?

**Comment by erikvanoosten** [comment]
That is not really possible because of how Dropwizard metrics works. Gauges (even cached gauges) should return as soon as possible because they are invoked synchronously while collecting data. If the future completes fairly quickly, you could just use Await.
If calculating the gauge value takes a long time you can also take the following approach: make your gauge simply return the value of some field. That field can be updated as a side effect of something else, or the calculation can be scheduled on some scheduler. If the field is not of some primitive type (Java terminology), you can wrap it in an Atomic*.
