### ISSUE TITLE
Question about gauges and class instantiation ("metric already exists")

### ISSUE THREAD

**Issue by gsastry** [erikvanoosten/metrics-scala#61]
Hi there,

I had a some counters in my app, declared like so:

```Scala
class Foo extends Instrumented {
val counter = metrics.counter("my-counter")
...
counter.inc(1)
```

and in my unit tests for `Foo`, I create a new instance of `Foo` before every tests, something like this:

```Scala
class Fixture {
      val foo = new Foo()
    }

    var f: Fixture = _

    before { f = new Fixture }

    def `test Foo 1 ` { ... }
   def `testFoo 2` { ... }
```

Now using counters, all the tests would run fine. I switched some of these counters to gauges, and my tests fail when the class throws the exception ("metric named my-counter already exists").

It appears that there's a method 
```java
private <T extends Metric> T getOrAdd(String name, MetricBuilder<T> builder)
```

that calling `metrics.gauge` skips, while `metrics.counters` does call it (and seems to grab the existing counter?

I'm confused why I'm seeing these differences between gauges and counters (and does that mean I can't multiple instances of the same class for gauges, because they'll throw?). I wanted to check with the metrics-scala library first before I ask the dropwizard folks in case anyone has any pointers. It seems like catching exception for the gauge and then reading the gauge with that name from the registry would be an anti pattern - seems like I'm misunderstanding something.

Thanks!

**Comment by erikvanoosten** [comment]
You are correct: Gauges can only be registered once, while Counters can be registered as often as you like (and you will always get the first one registered).

This is metrics-core behavior and not something I can change.

Although I don't know why the scenarios are different, I am guessing it is because Gauge objects are things you write yourself. There is no guarantee that you are passing the same Gauge instance every time. Counters, Timers, etc. are constructed by the library itself. Actually, metrics-core tries very hard not to instantiate duplicate Counters, Timers, etc. at all.

Closing this as there is nothing more I can do.

**Comment by erikvanoosten** [comment]
In #74 we're experimenting with a way to easily unregister gauges.
