### ISSUE TITLE
How does this project compare to datasift/dropwizard-scala?

### ISSUE THREAD

**Issue by jklukas** [erikvanoosten/metrics-scala#81]
It looks like datasift/dropwizard-scala project provides a metrics module for providing Scala-friendly access to dropwizard metrics. [That project is listed in Dropwizard's docs](http://www.dropwizard.io/1.0.0/docs/manual/scala.html) while [this project is listed in Dropwizard Metrics' docs](http://metrics.dropwizard.io/3.1.0/manual/third-party/).

Is there any relationship between the two packages, or are they simply different approaches to the same general concept?

**Comment by erikvanoosten** [comment]
I was not aware of this project. I will take a look this evening. Thanks for bringing it to our attention!

**Comment by erikvanoosten** [comment]
In Sep 2012 this project started as a line for line copy of the Metrics-scala module with the only difference that it was compiled for different scala versions. In Jun 2013 the Codahale/Dropwizard metrics project dropped the scala module in version 3.0.0. Since then this project developed independently.
Focus of this project is long term stability, correctness, easy to use API and full documentation (in that order).

Perhaps @nicktelford, the main author of dropwizard-scala would like to give some background about the datasift/dropwizard-scala project?

**Comment by erikvanoosten** [comment]
Hi @jklukas. I don't think its worthwhile to keep this open. If @nicktelford wants to answer here, or in https://github.com/datasift/dropwizard-scala/issues/13, he can still always do so.

**Comment by jklukas** [comment]
Sounds good. +1 for issue hygiene.

**Comment by nicktelford** [comment]
So my implementation is pretty lean, it looks like this project is far more extensive. I'm inclined to keep my sub-module around for the time-being as the API is a little different from what's defined here, and we use it rather a lot in my organization.

It shouldn't interfere with this project though, as you can just avoid importing my sub-module, and the size of the class(es) should be tiny.
