### ISSUE TITLE
Convert to multi-project sbt setup

### ISSUE THREAD

**Issue by erikvanoosten** [erikvanoosten/metrics-scala#84]
Currently we do magic to create specific releases for each scala version with or without Akka support. It would be better to split out Akka support to its own sub-project that depends on the metrics-core sub-project.

Ideally the names of the releases do not change.

Anyone who feels like taking this up is welcome to do so!

**Comment by brendon-** [comment]
Currently the akka and core versions have the same release names with differing versions.

To take advantage of sub-projects, 
I don't think you can have a sub-module (akka) that depends on another module (core) that have the same artifact org/name.   Essentially what the sub-projects setup does is publish each project independently, and you can use dependsOn in order to take one resource and include it as a dependency in another.  so each sub-project has to be distinguished as a unique org/name in order for the dependencies to actually make sense. 

Each would need to be identified as unique resources.  
Something like `metrics-scala`, and `metrics-akka` maybe?  I'm not sure what the conventions are here...  then `metrics-akka` dependsOn `metrics-scala` will get you what you want I think.

Discussion?

**Comment by erikvanoosten** [comment]
Hi @brendon-,

Yes of course, you are right. Thanks for making that clear. The names `metrics-scala` and `metrics-akka` it shall be then.
However, because of this name change I am going to wait till Dropwizard metrics 4.0.

Thanks!

**Comment by brendon-** [comment]
sure, happy to help when you are ready for this.

**Comment by erikvanoosten** [comment]
Hi @brendon- @scullxbones,

I am trying to break up the project into multiple libraries in order to simplify the build structure and reduce the number of released artifacts. At first I though that a simple multi-project structure would do. However, the `metrics-akka` library will need to be build multiple times for different Akka versions. Currently this is done external from sbt (see `crossrelease.sh`).

Then we have Hdr support. Even though its just a little bit of code, its cleaner to move this to its own library also.

These are the options I am seeing:

* Go extreme and switch to something else like Gradle. We'll need much more information to select this option.
* Keep as is, a single sbt project with different command line invocations to do akka cross builds.
* Keep everything in a single repository with sbt multi-project. The sub-projects will be called `metrics-scala`, `metrics-akka_2.4`, `metrics-akka_2.5` and `metrics-hdr`. We don't want to duplicate the Akka related sources, so somehow we need to convince sbt to build `metrics-akka` twice. We can probably do this by generating sbt projects on the fly and copying in the akka related sources. The big downside is that IDEs like IntelliJ probably won't understand virtual projects.
* Build separate sbt projects (either within the same git repository or separate). One project will compile `metrics-scala` and `metrics-hdr`, the other project will compile `metrics-akka`. We can use the same trick as currently to build for multiple Akka versions.

What are your thoughts on this? Do you see more options?

**Comment by scullxbones** [comment]
My opinion would be that akka 2.3 support can be left aside in the old releases of metrics-scala, and going forward, akka 2.4 and 2.5 support can be combined into a single sub-project `metrics-akka`.

Depending on exactly how it's done  I suppose that ends up being a vote for choice 3 or 4 above...

**Comment by erikvanoosten** [comment]
I found a fairly clean way to do scala/akka cross builds all from a single sbt multi-project.
