### ISSUE TITLE
Version Request: 3.5.9_a2.3  (with akka 2.4.19), or 3.5.9_a2.4 (against Scala 2.11)

### ISSUE THREAD

**Issue by ahepburn** [erikvanoosten/metrics-scala#97]
> If you need another version mix please open an issue

I'm able to use: 
`3.5.9_a2.3`  (with akka 2.4.19) by specifying an override
I'd like to use:
`3.5.9_a2.4`, but it isn't currently published for scala 2.11

Publishing either would be great (especially: 3.5.9_a2.4 for 2.11), neither is essential given the workaround, filed due to the note in the readme.

**Comment by erikvanoosten** [comment]
Hi @ahepburn , thanks for your interest in metrics-scala.

`3.5.9_a2.3` is specifically also suitable for Akka 2.4 and 2.5. So there is no real _need_ for having a version build against 2.4 (yes, I am slightly pedantic here ;) ).

I don't want to build tons of combination just so that a dependency in the pom has a given number. It is quite normal to use a different dependency then the one a library was build against. Even if metrics-scala was build against Akka 2.4.1, you would still use Akka 2.4.20.

Note that version 4.0.0 is in the works, any ideas or other feedback on #84 is appreciated.
